修复 form 重新渲染时 checkbox 自定义模版未正确获取的问题
layui/layui pull request #1257
Opened 2023-05-20 13:38 UTC by Sight-wcg

### 😃 本次 PR 的变化性质

> 请至少勾选一项（即 [ ] 内填写 x ）

- [ ] 功能新增
- [x] 问题修复
- [ ] 功能优化
- [ ] 分支合并
- [ ] 其他改动：请在此处填写

### 🌱 本次 PR 的变化内容

- [修复 form 重新渲染时 checkbox 自定义模版未正确获取的问题](https://github.com/layui/layui/commit/83392ec7ff628ed13567606dc39b7f081a564b88)

### ✅ 本次 PR 的满足条件

> 请在申请合并之前，将符合条件的每一项进行勾选（即 [ ] 内填写 x ）

- [x] 已提供在线演示地址（如：[codepen](https://codepen.io/)）或无需演示
- [x] 已对每一项的改动均测试通过
- [x] 已提供具体的变化内容说明

2023-05-21 11:16 UTC, sentsim requested changes

2023-05-21 11:16 UTC, sentsim commented on src/modules/form.js
> +            title = titleTemplate.html() || '';
在前几天制作官网深色主题的时候，我也发现了该问题，暂时的处理方案是重新渲染之前先移除已经渲染过的兄弟元素。

晨星的这个处理方式，还是存在一些不完美哈，比如同时放置多个 `checkbox`  时，且后面都跟着带有标题模板，那么这样直接查找兄弟元素就会匹配到很多个模板。建议还是先判断下一个兄弟元素是否是已经渲染过的元素，若渲染过，就将其移除即可。

2023-05-21 22:54 UTC, Sight-wcg commented on src/modules/form.js
> +            title = titleTemplate.html() || '';
缺实不够完善，我根据评论做了一些修改，感谢您的建议。

2023-05-22 01:50 UTC, sentsim commented on src/modules/form.js
> +            title = titleTemplate.html() || '';
@Sight-wcg 赞。

2023-05-22 01:51 UTC, merged