优化checkbox,switch 回调函数参数增加设置setChecked方法 Update form.js
layui/layui pull request #1304
Opened 2023-07-09 05:52 UTC by Diyar-IT

### 😃 本次 PR 的变化性质

> 请至少勾选一项（[ ] 内填写 x ）

- [ ] 功能新增
- [x] 问题修复
- [ ] 功能优化
- [ ] 分支合并
- [ ] 其他改动：请在此处填写

### 🌱 本次 PR 的变化内容

- 在此处列出本次 PR 的每一项改动内容

### ✅ 本次 PR 的满足条件

> 请在申请合并之前，将符合条件的每一项进行勾选（[ ] 内填写 x ）

- [ ] 已提供在线演示地址（如：[codepen](https://codepen.io/)）或无需演示
- [ ] 已对每一项的改动均测试通过
- [ ] 已提供具体的变化内容说明

2023-07-11 03:48 UTC, sentsim requested changes

2023-07-11 03:48 UTC, sentsim commented on src/modules/form.js
> +              setChecked: setChecked
事件中为何要增加这个方法呢？最好给出具体的应用场景。
个人认为可以直接给元素设置 `checked` 属性，再通过 `form.render()` 更新选中的显示状态。

2023-07-13 21:28 UTC, Diyar-IT commented on src/modules/form.js
> +              setChecked: setChecked
前几天遇到一个问题，table中用了layui switch，switch开启或关闭需要后台判断，所以。。。。

2023-08-08 07:55 UTC, sentsim commented on src/modules/form.js
> +              setChecked: setChecked
按照我上述说的直接给 `input` 设置 `checked` 属性，再进行 `form.render('checkbox')` 即可

2023-08-08 07:55 UTC, closed without merging