photos增加旋转，翻转，放大，缩小功能
layui/layui pull request #1339
Opened 2023-08-22 11:25 UTC by Diyar-IT

### 😃 本次 PR 的变化性质

> 请至少勾选一项（[ ] 内填写 x ）

- [ ] 功能新增
- [x] 问题修复
- [ ] 功能优化
- [ ] 分支合并
- [ ] 其他改动：请在此处填写

### 🌱 本次 PR 的变化内容

- 在此处列出本次 PR 的每一项改动内容

### ✅ 本次 PR 的满足条件

> 请在申请合并之前，将符合条件的每一项进行勾选（[ ] 内填写 x ）

- [ ] 已提供在线演示地址（如：[codepen](https://codepen.io/)）或无需演示
- [ ] 已对每一项的改动均测试通过
- [ ] 已提供具体的变化内容说明

2023-08-22 15:04 UTC, sentsim requested changes

2023-08-22 15:04 UTC, sentsim commented on src/modules/layer.js
> +	}
-  缩进需要重新排版
-  将编辑器中制表符设置成 2 个空格数替代

2023-08-22 15:04 UTC, sentsim commented on src/modules/layer.js
> +
将编辑器中制表符设置成 2 个空格数替代

2023-08-22 15:04 UTC, sentsim commented
很棒，该需求的确有不少人提过，原本是计划在后续的大版本中实现，既然已经提交了，可提前跟随 `2.8.16` 发布。不过，还是有以下一点建议：
- 后续应将 PR 提交到 `2.x` 分支：https://github.com/layui/layui/tree/2.x
- 与同一功能有所关联的文件，应放在同一个 PR 中一起提交，不要分开提交。
- Layui 的代码缩进用的一制表符等于 2 个空格数，为避免代码排版差异，建议将编辑器中的缩进设置成与 Layui 一致。

2023-08-23 08:22 UTC, Diyar-IT commented
> 很棒，该需求的确有不少人提过，原本是计划在后续的大版本中实现，既然已经提交了，看来可提前跟随 `2.8.16` 发布。
> 
> 不过，还是有以下几点建议：
> 
> * 后续应将 PR 提交到 `2.x` 分支：https://github.com/layui/layui/tree/2.x
> * 与同一功能有所关联的文件，应放在同一个 PR 中一起提交，不要分开提交。譬如应将 [增加photo工具栏样式 #1340](https://github.com/layui/layui/pull/1340) [增加了顶部工具栏说明 #1341](https://github.com/layui/layui/pull/1341) 合并到该 PR 中。
> * Layui 的代码缩进用的是一个制表符等于 2 个空格数，为避免代码排版差异，建议将编辑器中的缩进设置成与 Layui 一致。

以前不用git pull，我是git菜鸟请理解。。。

2023-08-23 12:12 UTC, Sight-wcg commented
是否考虑添加代码格式化工具，如果因为 tpl 模板语法不太方便加，[editorconfig](https://editorconfig.org/) 也可以

2023-08-23 12:12 UTC, Sight-wcg commented
是否考虑添加代码格式化工具，如果因为 tpl 模板语法不太方便加，[editorconfig](https://editorconfig.org/) 也可以

2023-08-23 14:29 UTC, sentsim commented
> 是否考虑添加代码格式化工具，如果因为 tpl 模板语法不太方便加，[editorconfig](https://editorconfig.org/) 也可以

已增加：https://github.com/layui/layui/blob/2.x/.editorconfig

2023-08-23 14:46 UTC, merged