Update tree.js
layui/layui pull request #1420
Opened 2023-11-01 12:38 UTC by 469888647

### 😃 本次 PR 的变化性质

> 请至少勾选一项

- [x] 功能新增
- [ ] 问题修复
- [ ] 功能优化
- [ ] 分支合并
- [ ] 其他改动：请在此处填写

### 🌱 本次 PR 的变化内容

- 在此处列出本次 PR 的每一项改动内容
> 组件tree增加下面的内容
- 增加对于数组对象式数据的支持:数据库对父子节点之间的关系可能是放在同一张表,以id和parentid进行关联，直接查出来只是一个列表。这里增加了方法,可以将这种数据处理成tree支持的依靠children的json嵌套的形式,增加了tree组件数据源的多样性。
- 增加一个配置项customName.parentid，这个主要是为了上面解析数组时指定parentid的名称的
- 增加了一个排序的配置项sort,默认是false,就和之前一样,设置为true的时候会对节点进行排序,它的子节点越多,这个节点越靠上方显示
- 在上一个配置项sort设置为true的情况下,新增一个配置项search，默认是空字符串，排序规则和上面一样;设置一个字符串就会用这个字符串在树里面查找匹配的项,匹配的是title展示的那一个属性，子节点匹配的次数越多,这个节点就越靠上，此外，被搜索的字符串会显示为高亮的红字进行提示

### ✅ 本次 PR 的满足条件

> 请在申请合并之前，将符合条件的每一项进行勾选

- [ ] 已提供在线演示地址（如：[codepen](https://codepen.io/), [stackblitz](https://stackblitz.com/)）或无需演示
- [✅] 已对每一项的改动均测试通过
- [✅] 已提供具体的变化内容说明

> 没有在线测试网站,使用的是本地的layuiDemo,测试方式如下:
- 随意打开一个layui的examples网页，在网页上面添加一个id为tree的div
- 创建一个数组 var list = [{id:1,title:'1',parentid:0},{id:2,title:'2',parentid:1},{id:3,title:'3',parentid:1},]
- 引入tree模块 layui.tree.render({elem:'#tree',data: list})
- 测试搜索 layui.tree.render({elem:'#tree',data: list,search:'3'})

2023-11-02 01:20 UTC, sentsim commented
关于 PR 满足 Merge 的基本条件，上次已在 #1410 发过了。

2023-11-02 01:20 UTC, sentsim approved these changes

2023-11-02 01:21 UTC, sentsim requested changes
1. Demo 可通过 [stackblitz](https://stackblitz.com/) 创建
2. 补充 docs 文件可参考：[#1410()](https://github.com/layui/layui/pull/1410#issuecomment-1783822339) 的第二点。

2023-11-03 03:08 UTC, 469888647 commented
1. 增加了对于tree文档的修改
2. stackblitz实在没有研究明白,所以是在examples的文件夹下面添加的测试例子

2023-11-03 03:28 UTC, 469888647 commented
> ### 😃 本次 PR 的变化性质
> > 请至少勾选一项
> 
> * [x]  功能新增
> * [ ]  问题修复
> * [ ]  功能优化
> * [ ]  分支合并
> * [ ]  其他改动：请在此处填写
> 
> ### 🌱 本次 PR 的变化内容
> * 在此处列出本次 PR 的每一项改动内容
> 
> > 组件tree增加下面的内容
> 
> * 增加对于数组对象式数据的支持:数据库对父子节点之间的关系可能是放在同一张表,以id和parentid进行关联，直接查出来只是一个列表。这里增加了方法,可以将这种数据处理成tree支持的依靠children的json嵌套的形式,增加了tree组件数据源的多样性。
> * 增加一个配置项customName.parentid，这个主要是为了上面解析数组时指定parentid的名称的
> * 增加了一个排序的配置项sort,默认是false,就和之前一样,设置为true的时候会对节点进行排序,它的子节点越多,这个节点越靠上方显示
> * 在上一个配置项sort设置为true的情况下,新增一个配置项search，默认是空字符串，排序规则和上面一样;设置一个字符串就会用这个字符串在树里面查找匹配的项,匹配的是title展示的那一个属性，子节点匹配的次数越多,这个节点就越靠上，此外，被搜索的字符串会显示为高亮的红字进行提示
> 
> ### ✅ 本次 PR 的满足条件
> > 请在申请合并之前，将符合条件的每一项进行勾选
> 
> * [ ]  已提供在线演示地址（如：[codepen](https://codepen.io/), [stackblitz](https://stackblitz.com/)）或无需演示
> * [✅] 已对每一项的改动均测试通过
> * [✅] 已提供具体的变化内容说明
> 
> > 没有在线测试网站,使用的是本地的layuiDemo,测试方式如下:
> 
> * 随意打开一个layui的examples网页，选择tree.html
> * 滚动到网页的下方
> * 第三个树的数据源就是一个数组形式的数据
> * 第四个树使用了搜索的功能，被搜索到的节点会展开靠上显示

2023-11-03 03:48 UTC, 469888647 commented
> ### 😃 本次 PR 的变化性质
> > 请至少勾选一项
> 
> * [x]  功能新增
> * [ ]  问题修复
> * [ ]  功能优化
> * [ ]  分支合并
> * [ ]  其他改动：请在此处填写
> 
> ### 🌱 本次 PR 的变化内容
> * 在此处列出本次 PR 的每一项改动内容
> 
> > 组件tree增加下面的内容
> 
> * 增加对于数组对象式数据的支持:数据库对父子节点之间的关系可能是放在同一张表,以id和parentid进行关联，直接查出来只是一个列表。这里增加了方法,可以将这种数据处理成tree支持的依靠children的json嵌套的形式,增加了tree组件数据源的多样性。
> * 增加一个配置项customName.parentid，这个主要是为了上面解析数组时指定parentid的名称的
> * 增加了一个排序的配置项sort,默认是false,就和之前一样,设置为true的时候会对节点进行排序,它的子节点越多,这个节点越靠上方显示
> * 在上一个配置项sort设置为true的情况下,新增一个配置项search，默认是空字符串，排序规则和上面一样;设置一个字符串就会用这个字符串在树里面查找匹配的项,匹配的是title展示的那一个属性，子节点匹配的次数越多,这个节点就越靠上，此外，被搜索的字符串会显示为高亮的红字进行提示
> 
> ### ✅ 本次 PR 的满足条件
> > 请在申请合并之前，将符合条件的每一项进行勾选
> 
> * [ ]  已提供在线演示地址（如：[codepen](https://codepen.io/), [stackblitz](https://stackblitz.com/)）或无需演示
> * [✅] 已对每一项的改动均测试通过
> * [✅] 已提供具体的变化内容说明
> 
> > 没有在线测试网站,使用的是本地的layuiDemo,测试方式如下:
> 
> * 随意打开一个layui的examples网页，选择tree.html
> * 滚动到网页的下方
> * 第三个树的数据源就是一个数组形式的数据
> * 第四个树使用了搜索的功能，被搜索到的节点会展开靠上显示

2023-11-03 06:20 UTC, 469888647 commented
> ### 😃 本次 PR 的变化性质
> > 请至少勾选一项
> 
> * [x]  功能新增
> * [ ]  问题修复
> * [ ]  功能优化
> * [ ]  分支合并
> * [ ]  其他改动：请在此处填写
> 
> ### 🌱 本次 PR 的变化内容
> * 在此处列出本次 PR 的每一项改动内容
> 
> > 组件tree增加下面的内容
> 
> * 增加对于数组对象式数据的支持:数据库对父子节点之间的关系可能是放在同一张表,以id和parentid进行关联，直接查出来只是一个列表。这里增加了方法,可以将这种数据处理成tree支持的依靠children的json嵌套的形式,增加了tree组件数据源的多样性。
> * 增加一个配置项customName.parentid，这个主要是为了上面解析数组时指定parentid的名称的
> * 增加了一个排序的配置项sort,默认是false,就和之前一样,设置为true的时候会对节点进行排序,它的子节点越多,这个节点越靠上方显示
> * 在上一个配置项sort设置为true的情况下,新增一个配置项search，默认是空字符串，排序规则和上面一样;设置一个字符串就会用这个字符串在树里面查找匹配的项,匹配的是title展示的那一个属性，子节点匹配的次数越多,这个节点就越靠上，此外，被搜索的字符串会显示为高亮的红字进行提示
> 
> ### ✅ 本次 PR 的满足条件
> > 请在申请合并之前，将符合条件的每一项进行勾选
> 
> * [ ]  已提供在线演示地址（如：[codepen](https://codepen.io/), [stackblitz](https://stackblitz.com/)）或无需演示
> * [✅] 已对每一项的改动均测试通过
> * [✅] 已提供具体的变化内容说明
> 
> > 没有在线测试网站,使用的是本地的layuiDemo,测试方式如下:
> 
> * 随意打开一个layui的examples网页，选择tree.html
> * 滚动到网页的下方
> * 第三个树的数据源就是一个数组形式的数据
> * 第四个树使用了搜索的功能，被搜索到的节点会展开靠上显示

2023-11-03 07:39 UTC, sentsim commented
@469888647  好的，辛苦了。由于当前已将 `2.8.18` 作为稳定版，在没有重要 BUG 的情况下，短期内应该不会频繁发布新版本。所以该 `PR` 可以慢慢完善细节。

2023-11-03 07:43 UTC, sentsim requested changes

2023-11-03 07:43 UTC, sentsim commented on docs/tree/detail/options.data.md
> +      <td>
此处版本标记应当改成： `2.9.0+`  ``

2023-11-03 07:43 UTC, sentsim commented on docs/tree/detail/options.md
> +      <td colspan="3">
`2.9.0+`

2023-11-03 07:43 UTC, sentsim commented on docs/tree/index.md
> +    parentid: 'parentid' // --- 2.8.18+
2.9.0+

2023-11-03 07:58 UTC, 469888647 commented
好的呢

2023-11-13 15:52 UTC, sentsim requested changes

2023-11-13 15:52 UTC, sentsim commented on src/modules/form.js
不建议在 form 中增加 select tree 功能，原因是 2.x 的 tree 组件本身是一个被边缘化的存在，将其加入到 form 中，会破坏 form 已有的稳定结构。该 PR 建议只针对 tree 组件本身的优化，而且是不对 tree 已有功能不产生影响的情况下。 

即：**2.x 的今后定位将是持续的稳定版，基本不会添加新功能，只限于问题修复。**
所有新功能都将放在 3.x 版本中。

2023-11-14 15:27 UTC, sentsim commented
@469888647 最好在 Forked 仓库建一个 `2.x-tree` 分支，并关联主仓库的 `2.x` 分支。
后续提交应当由 `469888647:2.x-tree` → [`layui:2.x`](https://github.com/layui/layui/tree/2.x)

![image](https://github.com/layui/layui/assets/3277200/152c6dd9-707d-4478-a0dd-65854893aaaa)

2023-12-31 15:41 UTC, sentsim commented
PR 已存在多项 conflicts，且相关功能与当前 `2.x` 版本定位存在出入，加上已有两个月未进行新的提交，暂时关闭。

2023-12-31 15:41 UTC, closed without merging