fix(layer): 修复鼠标悬停在某些元素上时，偶现细微偏移的问题
layui/layui pull request #1492
Opened 2023-12-23 15:32 UTC by Sight-wcg

### 😃 本次 PR 的变化性质

> 请至少勾选一项

- [ ] 功能新增
- [x] 问题修复
- [ ] 功能优化
- [ ] 分支合并
- [ ] 其他改动：请在此处填写

### 🌱 本次 PR 的变化内容

- fix(layer): 修复鼠标悬停在某些元素上时，偶现细微偏移的问题

### ✅ 本次 PR 的满足条件

> 请在申请合并之前，将符合条件的每一项进行勾选

- [ ] 已提供在线演示地址（如：[codepen](https://codepen.io/), [stackblitz](https://stackblitz.com/)）或无需演示
- [x] 已对每一项的改动均测试通过
- [x] 已提供具体的变化内容说明

2023-12-27 13:01 UTC, sentsim requested changes

2023-12-27 16:39 UTC, Sight-wcg commented on src/modules/layer.js
> +    }
#### hover 文字偏移相关的动画
rotate() 和 scale() 都会导致此问题，anim4 使用了 rotate()，所以 anim `2,5,6` 和 抽屉效果"的四个动画均不会出现 hover 文字偏移现象。

#### 为什么只排除 anim5
根据 [MDN-Containing_block](https://developer.mozilla.org/zh-CN/docs/Web/CSS/Containing_block) 中判断包含块的描述，移除了除 anim5 以外的判断，因为类似 layer.photos 的扩展，只能用 anim5 或者关闭出场动画。
- [transform](https://developer.mozilla.org/zh-CN/docs/Web/CSS/transform) 或 [perspective](https://developer.mozilla.org/zh-CN/docs/Web/CSS/perspective) 的值不是 none
- [will-change](https://developer.mozilla.org/zh-CN/docs/Web/CSS/will-change) 的值是 transform 或 perspective

#### 该 PR 存在的问题
该 PR 目前只有在非 anim5, 且在 layer success 回调中，对 layer content  添加 fixed 定位的元素的场景有影响。解决方案是将 layer 内部添加 will-change 的时机提前到 success 回调之前，以允许在 success 中移除 will-change，例如
```
success: function(layero){
  layero.css({ willChange: ''})
}
```

#### 其他可行的解决方案
由使用者主动在 success 回调(动画之前)执行 
```
success: function(layero){
  layero.css({ willChange: 'transform, top, left'})
}
```
#### 最后
综上，目前没有太完美的解决方案，要解决 #1471 总有一些场景要做出妥协。也许该 PR 可以暂时搁置，后续再看看有没有其他的解决方案，或者等待浏览器厂商修复。

2023-12-27 17:13 UTC, Sight-wcg commented on src/modules/layer.js
> +    }
经过考虑我认为这个 PR 存在的问题比较严重，例如 type 1 中使用了 fixed 定位的下拉菜单(其他库，例如 [xmSelect](https://maplemei.gitee.io/xm-select/#/senior/table))，就会影响菜单定位。实际上未测试到边界情况可能会更多，由于影响范围未知，我们不能合并这个 PR。

2023-12-28 01:53 UTC, sentsim commented on src/modules/layer.js
> +    }
是的，所以该 PR 我没有快速合并的原因，也是不大赞成内置 `willChange` 的解决方案，这里面涉及到利弊权衡，比如：它或许能解决 hover 文字轻微偏移，但却可能衍生其他的问题。刚好晨星发现了这一点，所以可行性是有待商榷的。

我还是建议类似的问题通过 `anim: 5` 规避，或视条件在外部追加 `willChange` 解决。

2023-12-28 02:53 UTC, Sight-wcg commented
关闭，因为该解决方案不合适。

2023-12-28 02:53 UTC, closed without merging