form新增loadSelect方法，用于动态渲染Select选项
layui/layui pull request #1588
Opened 2024-01-24 09:37 UTC by elylon1101

### 😃 本次 PR 的变化性质

> 请至少勾选一项

- [ ] 功能新增
- [x] 问题修复
- [ ] 功能优化
- [ ] 分支合并
- [ ] 其他改动：请在此处填写

### 🌱 本次 PR 的变化内容
在form模块中新增了一个loadSelect方法，用于动态加载select的option选项
![image](https://github.com/layui/layui/assets/54056210/420727ba-8148-46b6-960e-ef84cc7506db)

在examples/form.html提供了对应的测试demo

### ✅ 本次 PR 的满足条件

> 请在申请合并之前，将符合条件的每一项进行勾选

- [ ] 已提供在线演示地址（如：[codepen](https://codepen.io/), [stackblitz](https://stackblitz.com/)）或无需演示
- [x] 已对每一项的改动均测试通过
- [ ] 已提供具体的变化内容说明

2024-01-25 04:20 UTC, Sight-wcg requested changes

2024-01-25 04:20 UTC, Sight-wcg commented on src/modules/form.js
> +    let dom = options.data.map(item => `<option value="${ item[options.valueKey] }" ${ item[options.valueKey] === options.selectValue ? 'selected ' : '' }>${ options.getShow ? options.getShow(item) :
只能使用 ES5 语法

2024-01-25 04:20 UTC, Sight-wcg commented on src/modules/form.js
> +    let el = layui.$(options.selector);
```suggestion
    let el = $(options.selector);
```

2024-01-25 04:20 UTC, Sight-wcg commented on src/modules/form.js
> +      el.append(`<option value="${ options.defaultValue }">${ options.defaultText }</option>`);
改为 ES5 语法

2024-01-25 04:20 UTC, Sight-wcg commented on src/modules/form.js
> +    this.render('select')
```suggestion
    this.render(el)
```
可以使用定向渲染，减少不必要的更新

2024-01-25 04:20 UTC, Sight-wcg commented on src/modules/form.js
> +   * @property {string} selector DOM选择器
建议 selector 改为 elem, 尽可能和其他组件保持一致的风格

2024-01-25 04:26 UTC, Sight-wcg commented
我觉得在外部封装下就可以了

2024-01-30 10:22 UTC, sentsim commented
建议直接在外部实现 select 选项的动态加载。

2024-01-30 10:22 UTC, closed without merging