feat(dropdown): 新增 close 选项
layui/layui pull request #1605
Opened 2024-01-30 04:49 UTC by Sight-wcg

### 😃 本次 PR 的变化性质

> 请至少勾选一项

- [x] 功能新增
- [ ] 问题修复
- [ ] 功能优化
- [ ] 分支合并
- [ ] 其他改动：请在此处填写

### 🌱 本次 PR 的变化内容

- 新增 close 选项

### ✅ 本次 PR 的满足条件

> 请在申请合并之前，将符合条件的每一项进行勾选

- [ ] 已提供在线演示地址（如：[codepen](https://codepen.io/), [stackblitz](https://stackblitz.com/)）或无需演示
- [x] 已对每一项的改动均测试通过
- [x] 已提供具体的变化内容说明

2024-01-30 11:32 UTC, Sight-wcg commented
这么做可能不安全，我尝试一下别的方案。

2024-02-25 09:53 UTC, sentsim requested changes

2024-02-25 09:53 UTC, sentsim commented on src/modules/dropdown.js
> +      }
将 `options` 存储在目标元素上可能并不是实现 `close` 回调所必须的。
```suggestion
```

2024-02-25 09:53 UTC, sentsim commented on src/modules/dropdown.js
> +      }
这里可能是被 `prevElem` 误导了，直接操作原型链是否也能达到目的呢，晨星可做进一步验证。
```suggestion
      var prevElem = elemPrev.data('prevElem');
      if (prevElem) {
        prevElem.data(MOD_INDEX +'_opened', false);
      }
```

2024-02-25 09:53 UTC, sentsim commented on src/modules/dropdown.js
>        elemPrev.remove();
```suggestion
      elemPrev.remove();

      delete thisModule.prevElem;
      typeof options.close === 'function' && options.close();
    }
```

2024-02-25 09:56 UTC, sentsim requested changes

2024-02-25 09:56 UTC, sentsim commented on src/modules/dropdown.js
>        elemPrev.remove();
这里可能是被 `prevElem` 误导了，直接操作原型链是否也能达到目的呢，晨星可做进一步验证。

```suggestion
      var prevElem = elemPrev.data('prevElem');
      if (prevElem) {
        prevElem.data(MOD_INDEX +'_opened', false);
      }
      elemPrev.remove();
      delete thisModule.prevElem;
      typeof options.close === 'function' && options.close(prevElem);
```

2024-02-25 14:46 UTC, Sight-wcg commented on src/modules/dropdown.js
>        elemPrev.remove();
如果直接操作原型链，以下场景将无法正常触发 close 事件
1. 点击 A, A 打开
2. 鼠标悬停 B，A 关闭，B 打开

此时 A 关闭调用的是 B 的 close 事件
```  js
dropdown.render({
    elem: '#demoA'
    ,content: '自定义内容  123 '
    ,trigger: 'click'
    ,close: function(){
      console.log('demoA', this.elem);
    }
});
dropdown.render({
    elem: '#demoB'
    ,content: '自定义内容  123 '
    ,trigger: 'hover'
    ,close: function(){
      console.log('demoB', this.elem);
    }
});
```

2024-02-27 09:57 UTC, sentsim approved these changes

2024-02-27 09:57 UTC, sentsim commented on src/modules/dropdown.js
> +      var prevOnClose = prevInstance.config.close;
赞，这才是最佳方案。

2024-02-27 09:59 UTC, sentsim approved these changes

2024-02-27 09:59 UTC, merged