修复多个文件上传时能选择同样文件问题
layui/layui pull request #1757
Opened 2024-04-04 12:54 UTC by Diyar-IT

### 😃 本次 PR 的变化性质

> 请至少勾选一项

- [ ] 功能新增
- [x] 问题修复
- [ ] 功能优化
- [ ] 分支合并
- [ ] 其他改动：请在此处填写

### 🌱 本次 PR 的变化内容

修复多文件上传时选择一个文件后再次点击选择按钮直接取消，再次选择选择同一个文件时允许加入上传排队问题

### ✅ 本次 PR 的满足条件

> 请在申请合并之前，将符合条件的每一项进行勾选

- [ ] 已提供在线演示地址（如：[codepen](https://codepen.io/), [stackblitz](https://stackblitz.com/)）或无需演示
- [ ] 已对每一项的改动均测试通过
- [ ] 已提供具体的变化内容说明

2024-04-12 10:16 UTC, sentsim commented
赞，确实存在该问题。

2024-04-16 11:48 UTC, sentsim commented
我近期公司项目较忙，有劳晨星@Sight-wcg、青崖@bxjt123 负责下 PR 的 Review 工作。
Merge  由晨星同学统一把控。

2024-04-17 03:25 UTC, Sight-wcg requested changes

2024-04-17 03:25 UTC, Sight-wcg commented on src/modules/upload.js
> +      var formatSize = typeof value === 'string' ? parseFloat(size + '') : size;
```suggestion
      var formatSize = typeof size === 'string' ? parseFloat(size + '') : size;
```

2024-04-17 03:25 UTC, Sight-wcg commented on src/modules/upload.js
> +     * @param {number|float} size -文件大小
```suggestion
     * @param {number | string} size -文件大小
```

2024-04-17 03:27 UTC, Sight-wcg commented
> 我近期公司项目较忙，有劳晨星@Sight-wcg、青崖@bxjt123 负责下 PR 的 Review 工作。 Merge 由晨星同学统一把控。我也会抽空定期参与。

好的，有时间会看一下，合并由您操作。

2024-04-25 02:35 UTC, Sight-wcg approved these changes

2024-04-26 08:29 UTC, merged