增加小数滑块
layui/layui pull request #1794
Opened 2024-04-16 01:06 UTC by Diyar-IT

### 😃 本次 PR 的变化性质

> 请至少勾选一项

- [x ] 功能新增
- [ ] 问题修复
- [ ] 功能优化
- [ ] 分支合并
- [ ] 其他改动：请在此处填写

### 🌱 本次 PR 的变化内容
效果：
![微信截图_20240416090537](https://github.com/layui/layui/assets/136627746/8a75e294-4305-4433-8c8d-a3f98f319ef7)

- 在此处列出本次 PR 的每一项改动内容

### ✅ 本次 PR 的满足条件

> 请在申请合并之前，将符合条件的每一项进行勾选

- [ ] 已提供在线演示地址（如：[codepen](https://codepen.io/), [stackblitz](https://stackblitz.com/)）或无需演示
- [ ] 已对每一项的改动均测试通过
- [ ] 已提供具体的变化内容说明

2024-04-16 12:11 UTC, sentsim commented
@Diyar-IT  后续 PR 标题及 Commit message 按照统一格式规范书写，可大致遵循 Angular 团队的 Commit 规范即可。

```
<type>(<scope>): <subject>
```

- type:  commit 的类型
- scope: commit 影响的范围
- subject: commit 的简短描述`

如：feat(slider): 增加小数滑块

2024-04-17 04:22 UTC, Sight-wcg requested changes
当设置 `type: 'vertical'`， `range: 'vertical'`  时，效果不符合预期，同时建议用一个选项来设置是否开启此效果。

2024-04-17 04:22 UTC, Sight-wcg commented on src/modules/slider.js
> +    if (options.min < 0 && options.step >= 1) options.step = 0.01;
为什么要将 step 设置为 0.01?

2024-04-17 04:22 UTC, Sight-wcg commented on src/modules/slider.js
>        if(options.type === 'vertical'){
当设置 `type: 'vertical' ` 时，效果和 `type: 'default'` 不一致

2024-04-17 04:22 UTC, Sight-wcg commented on src/modules/slider.js
> +      if (options.min < 0) {
`range: true` 时应该不需要处理滑块偏移

2024-04-17 04:22 UTC, Sight-wcg commented on src/modules/slider.js
> +          if (options.min < 0) {
`range: true` 时应该不需要处理滑块偏移

2024-04-17 04:22 UTC, Sight-wcg commented on src/modules/slider.js
> +        if (options.min < 0) {
`range: true` 时应该不需要处理滑块偏移

2024-04-24 09:34 UTC, sentsim requested changes
@Diyar-IT  有空记得将晨星上述的 Review 逐一处理。

2024-05-02 09:32 UTC, Diyar-IT commented
> @Diyar-IT 有空记得将晨星上述的 Review 逐一处理。
好的，最近有一点忙，有空就优惠代码。。。

2024-05-23 07:39 UTC, sentsim commented
由于该 PR 超过一个月未按照要求更改，先做关闭。
后续若有更好的优化方案，欢迎再次提交。

2024-05-23 07:39 UTC, closed without merging