重写列宽度计算方式，以实际内容宽度为准
layui/layui pull request #1900
Opened 2024-05-13 15:06 UTC by 15810208908

### 😃 本次 PR 的变化性质

> 请至少勾选一项
- [x] 功能优化
- [x] 分支合并

### 🌱 本次 PR 的变化内容

- 新增width参数支持：auto值
- 重写列宽度计算方式，以每行数据所占用的实际宽度为准，但不超过设定的最大宽度值；
- 新增nowrap参数，指定当内容宽度超过所设定的列宽度时，进行强制换行，更好的视觉呈现

### ✅ 本次 PR 的满足条件

> 请在申请合并之前，将符合条件的每一项进行勾选

- [x] 已对每一项的改动均测试通过
- [x] 已提供具体的变化内容说明

2024-05-14 08:55 UTC, Sight-wcg commented
感谢您的 PR
- 建议增加一个选项来设置列宽分配策略，因为根据单元格实际内容宽度分配列宽，性能受行数影响
- 不同的问题建议拆分为单个 PR 来解决，一个 PR 尽量只解决一个问题
- 请恢复代码格式。也许 layui 需要配置 lint 工具

2024-05-15 09:03 UTC, 15810208908 commented
> 谢谢你的公关
> 
> * 建议增加一个选项来设置列分配策略，因为根据单元格实际内容宽度分配列宽，性能受行数影响
> * 不同的问题建议拆分为单个 PR 来解决，一个 PR 尽量只解决一个问题
> * 请恢复代码格式。也​​​​许layui 需要配置lint工具

经过这几天使用表格相关的功能，现已优化到最佳状态了，扩展或优化了一些常用功能，实际效果：
![image](https://github.com/layui/layui/assets/20258462/e4c14eda-a7a9-4b7b-bbec-ca652f56aacc)

2024-05-15 09:06 UTC, 15810208908 commented
> > 谢谢你的公关
> > 
> > * 建议增加一个选项来设置列分配策略，因为根据单元格实际内容宽度分配列宽，性能受行数影响
> > * 不同的问题建议拆分为单个 PR 来解决，一个 PR 尽量只解决一个问题
> > * 请恢复代码格式。也​​​​​​许layui 需要配置lint工具
> 
> 经过这几天使用表格相关的功能，现已优化到最佳状态了，扩展或优化了一些常用的功能，实际效果： ![图像](https://private-user-images.githubusercontent.com/20258462/330737158-e4c14eda-a7a9-4b7b-bbec-ca652f56aacc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU3NjQxMDEsIm5iZiI6MTcxNTc2MzgwMSwicGF0aCI6Ii8yMDI1ODQ2Mi8zMzA3MzcxNTgtZTRjMTRlZGEtYTdhOS00YjdiLWJiZWMtY2E2NTJmNTZhYWNjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTE1VDA5MDMyMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTcyMjZkOTBjMzQ2YTA2M2RhY2YzY2VhZWRkMDRkZjdlZmY5MDJhY2I4NmE0YjhkNDU5YjczMDUwNmY5ODNhNzUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.WamhkwZFMg6LA_woYDadLuFdu-UBuifk9pmfj5ind0U)

建议合并我所有提交的代码，可能用部份改动影响初始值；但不建议增加多分支的方式，我认为这样能提高性能；关于代码格式，我直接使用的Visual Studio，而VScode 的代码格式方式真的是一言难尽了。。。

2024-05-15 09:37 UTC, 15810208908 commented
> ### 😃 本次 PR 的变化性质
> > 请至少勾选一项
> 
> * [x]  功能优化
> * [x]  分支合并
> 
> ### 🌱 本次 PR 的变化内容
> * 新增width参数支持：auto值
> * 重写列宽度计算方式，以每行数据所占用的实际宽度为准，但不超过设定的最大宽度值；
> * 新增nowrap参数，指定当内容宽度超过所设定的列宽度时，进行强制换行，更好的视觉呈现
> 
> ### ✅ 本次 PR 的满足条件
> > 请在申请合并之前，将符合条件的每一项进行勾选
> 
> * [x]  已对每一项的改动均测试通过
> * [x]  已提供具体的变化内容说明
> 
> 使用实例：
> 
> > 
> 
> > 
> 
> > layui.use(function () {
> > var table = layui.table;
> > table.render({
> > elem: "#datalist",
> > toolbar: [  //优化后的自定义工具栏
> > {
> > "icon": "layui-icon-add-1",
> > "text": "增加",
> > "handler": function () {
> > alert("")
> > }
> > },
> > "-",  //分割符
> > ],
> > page: {  //优化后的分页处理方式
> > curr: handler.curpage,
> > count: json.rowcount,
> > limit: handler.pagesize,
> > onselect: function (curpage, pagesize) {
> > handler.curpage = curpage;
> > handler.pagesize = pagesize;
> > handler.getdata();
> > }
> > },
> > cols: [[
> > {
> > title: 'ID',
> > field: 'order_id',
> > },
> > {
> > title: '事项',
> > field: 'modelname',
> > },
> > {
> > title: '状态',
> > field: 'statetxt',
> > },
> > {
> > title: '录入时间',
> > field: 'shijian',
> > },
> > {
> > title: '收费日期',
> > field: 'paydt',
> > },
> > {
> > title: '会员姓名',
> > field: 'realname',
> > },
> > {
> > title: '卡名称',
> > field: 'title',
> > align: 'left',
> > },
> > {
> > title: '店铺名称',
> > field: 'storetitle',
> > },
> > {
> > title: '录入',
> > field: 'staffrealname',
> > },
> > {
> > title: '销售',
> > field: 'salerealname',
> > },
> > {
> > title: '费用',
> > field: 'order_realfee',
> > },
> > {
> > title: '备注',
> > field: 'summary',
> > align: 'left',
> > width: 'auto',  //自动列宽，其他未设置列按内容计算实际宽度，整个容器宽度减去其他列宽后剩余宽度给此列，如果多列使用'auto'，进行平均分配；如果剩余的列宽不够自动分配，则按实际宽度进行处理
> > nowrap: false,
> > },
> > ]],
> > onClickPayTime: function (index, rows, cols) { // //自定义事件
> > ordertoolkit.openupdatepaydt(rows.orderid, function () {
> > handler.getdata();
> > });
> > },
> > onClickAmount: function (index, rows, cols) {  //自定义事件
> > ordertoolkit.openupdateamount(rows.orderid, function () {
> > handler.getdata();
> > });
> > },
> > "data": data
> > });
> > });

2024-05-15 13:31 UTC, sentsim requested changes

2024-05-15 13:31 UTC, sentsim commented on src/css/layui.css
包含太多 CSS 空格的变动，可能是编辑器进行了格式化处理，建议在本次 PR 中移除 `layui.css`。

2024-05-15 13:33 UTC, sentsim requested changes

2024-05-15 13:33 UTC, sentsim commented on src/modules/table.js
`table.js` 存在提交记录的冲突

2024-05-15 13:40 UTC, sentsim commented
该 PR 由于文件内容出现了大量格式化的差异，以及存在代码冲突，难以进行 Review。暂时设置为 Draft 状态。

2024-05-16 02:43 UTC, 15810208908 commented
另外增加一个表格布局：工具栏及分页栏上下固定的CSS：

.layui-table-view { position: absolute; top: 0; left: 0; right: 0; bottom: 0; }
.layui-table-box { position: absolute; top: 0; left: 0; right: 0; bottom: 45px; z-index: 1; }
.layui-table-body { position: absolute; top: 41px; left: 0; right: 0; bottom: 0; }
.layui-table-page { position: absolute; left: 0; bottom: 0; right: 0; }
.layui-laypage span, .layui-laypage a { font-size: 14px; }
.layui-table-cell { text-align: center; }
.layui-table-tool { position: absolute; top: 0; left: 0; right: 0; height: 45px; min-height: initial; line-height: normal; padding: 8px; overflow: hidden; }
.layui-table-tool + .layui-table-box { top: 46px; }
.layui-table-body .layui-none { text-align: left; }
.layui-table-header .layui-table-cell { white-space: normal; text-overflow: inherit; overflow: visible; }

2024-05-16 02:47 UTC, 15810208908 commented on src/css/layui.css
因为工具不一致导致，我用的Visual Studio，这工具对CSS格式化的时候在值前面加空格了

2024-05-16 02:59 UTC, 15810208908 commented on src/modules/table.js
主要是我重写了不少地方的代码，以及增加了不少新功能与其他版本冲突吧；可以直接用的版本，
重写的部分：单元格的宽度计算，改成了以多行数据中的最多数据实际长度（但不大于设定的最大列宽）作为列宽度，主要是为了让数据能直观全部呈现出来，当大于列宽的时候自动换行或溢出（以nowrap参数控制）；重写分页处理逻辑及增加当选择或改变页码时执行onselect时间，这样更适合在各环境中兼容使用；增加在表格数据渲染时的options中增加自定义事件，不用在额外用layui.event进行处理，这样方便上下文的数据引用及处理；具体可看一下我的代码版本以及对未来其他模块进行重写以及采用我的思路，让使用起来更快捷简便。
![image](https://github.com/layui/layui/assets/20258462/0b0082a0-a1a6-4df6-9039-3d1890dd5d8a)
![image](https://github.com/layui/layui/assets/20258462/c8a303b2-356e-45be-936a-43855639f3ea)
![image](https://github.com/layui/layui/assets/20258462/6de06151-c2e7-4f80-9f90-fa6432f2436a)

2024-05-17 09:40 UTC, 15810208908 commented
相关更新后的实例：
![image](https://github.com/layui/layui/assets/20258462/ec88e85c-7ff3-48ff-8f0e-53c4418460be)

2024-05-17 09:43 UTC, 15810208908 commented
实际界面：
![image](https://github.com/layui/layui/assets/20258462/96db152a-19c8-4a5c-82c5-95b2b423c746)

2024-05-17 11:57 UTC, sentsim requested changes
感谢您的贡献。
由于编辑器对代码进行了格式化处理，导致文本差异过大，难以进行 review，该 PR 先关闭。

建议：**同步仓库 `main` 的最新代码**（避免代码冲突），在本地使用 **VScode** 或 **Sublime Text** 编辑器修改，再重新创建 PR。谢谢。

2024-05-17 12:09 UTC, sentsim commented
接下来会对 Layui 配置 Prettier，以保证代码格式的统一。

2024-05-17 12:09 UTC, closed without merging

2024-05-22 02:12 UTC, hulang commented
之前一直用Visual Studio，现在用vs code，vs code的格式代码，可以的啊。。