feat(form-select): 新增 `lay-append-to-body` 属性
layui/layui pull request #1926
Opened 2024-05-20 21:43 UTC by Sight-wcg

### 😃 本次 PR 的变化性质

> 请至少勾选一项

- [x] 功能新增
- [ ] 问题修复
- [ ] 功能优化
- [ ] 分支合并
- [ ] 其他改动：请在此处填写

### 🌱 本次 PR 的变化内容

- feat(form-select): 新增 `lay-append-to-body` 属性

### ✅ 本次 PR 的满足条件

> 请在申请合并之前，将符合条件的每一项进行勾选

- [x] 已提供在线演示地址（如：[codepen](https://codepen.io/), [stackblitz](https://stackblitz.com/)）或无需演示
- [x] 已对每一项的改动均测试通过
- [x] 已提供具体的变化内容说明

2024-05-20 21:47 UTC, Sight-wcg commented
如果该 PR 可以合并，最好将新增的 `lay-append-to-body` 属性标记为实验性。

2024-05-21 01:23 UTC, sentsim commented
完全可以合并。晨星终于实现了我一直想做，而却因为执行率不够没能做的。
我甚至认为可以不必保留原先在 form 初始渲染时将元素生成在表单元素后的模式，而是直接采用该 PR 实现的生成在 body 中，即跟 dropdown 一样动态生成，避免给 form 结构造成过多的节点负担，尤其是在 select 选项数量很多的情况下。

2024-05-21 13:53 UTC, sentsim commented
确实如此，那还是以向下兼容为主，以避免出现不必要的破坏性升级。

2024-05-23 03:51 UTC, bxjt123 commented
有一个小疑问，在`layer`里使用`<select lay-append-to-body>`下拉框会随着浏览器滚动条而滚动，需要额外设置一个`scrollbar: false`避免，而在`layer`里使用`laydate`也是面板会随着浏览器滚动条而滚动，这个是因为定位的关系吗

2024-05-23 06:28 UTC, Sight-wcg commented
> 有一个小疑问，在`layer`里使用`<select lay-append-to-body>`下拉框会随着浏览器滚动条而滚动，需要额外设置一个`scrollbar: false`避免，而在`layer`里使用`laydate`也是面板会随着浏览器滚动条而滚动，这个是因为定位的关系吗

这是因为在 layer 中使用时，触发元素和被定位的面板元素不在同一个滚动容器中。
一般可以通过将定位元素 appenTo 到和触发元素相同的滚动容器，或者收集触发元素父级所有滚动容器，添加滚动事件监听，滚动时更新定位元素的位置。

2024-05-24 00:26 UTC, Sight-wcg commented
> > 有一个小疑问，在`layer`里使用`<select lay-append-to-body>`下拉框会随着浏览器滚动条而滚动，需要额外设置一个`scrollbar: false`避免，而在`layer`里使用`laydate`也是面板会随着浏览器滚动条而滚动，这个是因为定位的关系吗
> 
> 这是因为在 layer 中使用时，触发元素和被定位的面板元素不在同一个滚动容器中。 一般可以通过将定位元素 appenTo 到和触发元素相同的滚动容器，或者收集触发元素父级所有滚动容器，添加滚动事件监听，滚动时更新定位元素的位置。

和定位，滚动容器都有关系，layer 默认是 fixed 定位，lay.position 默认是 absolute。目前如果想解决这个问题，可以监听父级所有滚动容器更新面板位置，或者下面的补丁。

```
      //  <script src="https://unpkg.com/@popperjs/core@2"></script>
      //  在 layui 之后引入这段代码, 依赖 popperjs。
      lay.position = function (triggerEl, contentEl, options) {
        if (contentEl.__popperInstance__) return;
        // normalize options
        var clickType = lay.isTopElem(triggerEl) ? 'right' : (options.clickType || 'left');
        var offset = options.offset || [0, 5];
        var position = options.position || 'absolute';
        var eventObject = options.e || window.event || {};
        var placement = {
          left: 'bottom-start',
          right: 'bottom-end',
          center: 'bottom'
        }[options.align || 'left'];

        var popperOptions = {
          placement: placement,
          strategy: position,
          modifiers: [
            {
              name: 'offset',
              options: {
                offset: offset,
              },
            },
            {
              name: 'computeStyles',
              options: {
                gpuAcceleration: false, // 关闭 GPU 加速，一些动画影响 3D transforms
              },
            },
          ],
        }


        if (clickType === 'right') {
          var e = eventObject;
          var virtualElement = {
            getBoundingClientRect: function () {
              return {
                width: 0,
                height: 0,
                left: e.clientX,
                top: e.clientY,
                right: e.clientX,
                bottom: e.clientY
              }
            },
          };
          contentEl.__popperInstance__ = Popper.createPopper(virtualElement, contentEl, popperOptions)
        } else {
          contentEl.__popperInstance__ = Popper.createPopper(triggerEl, contentEl, popperOptions);
        }

        // layui 中所有面板都是点击外部关闭，所以监听 contentEl 外部的点击，销毁 popper 实例
        var stop = lay.onClickOutside(contentEl, function () {
          contentEl.__popperInstance__.destroy();
          contentEl.__popperInstance__ = null;
          stop();
        }, { ignore: clickType === 'right' ? undefined : [triggerEl] });
      }
```

2024-05-24 05:38 UTC, bxjt123 commented
> 和定位，滚动容器都有关系，layer 默认是 fixed 定位，lay.position 默认是 absolute。目前如果想解决这个问题，可以监听父级所有滚动容器更新面板位置，或者下面的补丁。

学到了，感谢解惑

2024-05-27 15:30 UTC, Sight-wcg commented
> 有一个小疑问，在`layer`里使用`<select lay-append-to-body>`下拉框会随着浏览器滚动条而滚动，需要额外设置一个`scrollbar: false`避免，而在`layer`里使用`laydate`也是面板会随着浏览器滚动条而滚动，这个是因为定位的关系吗

如果将来打算解决 triggerEl 和 contentEl 不在同一滚动容器或 triggerEl 在 fixed 定位的容器中，滚动同步位置的问题，这个 PR 可能就没有必要了😅。
因为只能用 「监听父级所有滚动容器更新面板位置」的方法来修复(也有缺点，triggerEl 处于 fixed 定位容器中，contentEl 必须用 fixed 定位，否则会contentEl 会抖动)，这样的话，select 面板使用 fixed 定位就可以解决大部分情况下处于 overflow:hiden 容器被裁剪的问题。
所以我在考虑，是否有必要继续这个 PR？fixed 定位有什么缺点吗？🤔

2024-05-31 10:29 UTC, d8q8 commented
> 如果该 PR 可以合并，最好将新增的 `lay-append-to-body` 属性标记为实验性。

好像表格中把那个.layui-table-cell样式的overflow改成visible也行
.layui-table-cell {
     overflow: visible !important;
}
或者在表格渲染完成事件done中加入
$(".layui-table-cell").css('overflow','visible');

2024-05-31 13:53 UTC, Sight-wcg commented
> > 如果该 PR 可以合并，最好将新增的 `lay-append-to-body` 属性标记为实验性。
> 
> 好像表格中把那个.layui-table-cell样式的overflow改成visible也行 .layui-table-cell { overflow: visible !important; } 或者在表格渲染完成事件done中加入 $(".layui-table-cell").css('overflow','visible'); 这个只能控制单元格，表格外层同样要处理
> 
> 看来下面这几个都要处理，上面的CSS也要处理 $(".layui-table-body,.layui-table-box,.layui-table-cell").css('overflow','visible');

类似方案限制比较多，一些情况会导致单元格，表格容器出现滚动条。layer 中如果内容高度不定，可能会导致内容溢出 layer 容器。

2024-06-05 11:49 UTC, sentsim commented
考虑到 `2.9.11` 已包含数量适中的内容变更，以及晨星可能还对此存在一些优化调整，该 PR 实现的功能将跟随 `2.9.12` 发布。

2024-06-05 14:11 UTC, Sight-wcg commented
> 考虑到 `2.9.11` 已包含数量适中的内容变更，以及晨星可能还对此存在一些优化调整，该 PR 实现的功能将跟随 `2.9.12` 发布。



> 考虑到 `2.9.11` 已包含数量适中的内容变更，以及晨星可能还对此存在一些优化调整，该 PR 实现的功能将跟随 `2.9.12` 发布。

好的

2024-06-17 01:36 UTC, sentsim commented
在 layer 等采用 `position: fixed` 定位的容器中对 `select` 使用 `lay-append-to` 的方式时， 还需要考虑通过鼠标滚轮滑动滚动条时导致的 `select` 错位，这是 `lay.onClickOutside` 方法无法覆盖到的。因此，有必要增加一个 `lay-append-position` 属性，用于设置 `select` 面板与主容器保持相同的定位方式，避免错位。

> 其他组件（如 laydate, dropdown, colorpicker）也提供了相关选项来规避。
> 不过刚好发现 dropdown, colorpicker 组件都没有把 `position` 选项写进文档 😅，发版前将顺带补充 。

2024-06-17 01:36 UTC, sentsim requested changes
在 layer 等采用 `position: fixed` 定位的容器中对 `select` 使用 `lay-append-to` 的方式时， 还需要考虑通过鼠标滚轮滑动滚动条时导致的 `select` 错位（如图所示)，这是 `lay.onClickOutside` 方法无法覆盖到的。因此，有必要增加一个 `lay-append-position` 属性，用于设置 `select` 面板与主容器保持相同的定位方式，避免错位。

![image](https://github.com/layui/layui/assets/3277200/00d27999-2f49-4ae8-bee0-961494ee7a38)

> 其他组件（如 laydate, dropdown, colorpicker）也提供了相关选项来规避。
> 不过刚好发现 dropdown, colorpicker 组件都没有把 `position` 选项写进文档 😅，发版前将顺带补充 。

2024-06-17 01:58 UTC, sentsim commented
@bxjt123 之前没有细看青崖的描述。
laydate 可以通过设置 `position: 'fixed'` 保持与 layer 的定位方式相同来规避该问题，文档中也有相关介绍。

2024-06-17 02:21 UTC, sentsim commented on src/modules/form.js
> +                  position: appendPosition || null,
```suggestion
                  position: appendPosition,
```

2024-06-17 02:29 UTC, sentsim approved these changes

2024-06-17 06:08 UTC, bxjt123 commented
> @bxjt123 之前我没有细看青崖的描述。 laydate 可以通过设置 `position: 'fixed'` 保持与 layer 的定位方式相同来规避该问题，文档中也有相关介绍。 ![image](https://private-user-images.githubusercontent.com/3277200/340157860-aee69a48-ce94-4c30-a053-7f68e1550d0d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg2MDM0MTMsIm5iZiI6MTcxODYwMzExMywicGF0aCI6Ii8zMjc3MjAwLzM0MDE1Nzg2MC1hZWU2OWE0OC1jZTk0LTRjMzAtYTA1My03ZjY4ZTE1NTBkMGQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDYxNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA2MTdUMDU0NTEzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MzEwOGU2M2Y5MDViNjdhMjU3NmFlNmY0OTY4ODUwMzU4MTliZjc3ZmRhNjdjYzgzYzgwYjI2Nzc5ZWJhYTNmMSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.5jCNKlFkdV2EGjFXsldcqxQPIzUJB5n5vW6wuEgU9n0)

可能我给记混了，在`layer`弹窗里自带滚动条时，`laydate`的`position`不管怎么设置，打开面板后，鼠标滚轮滚动`layer`里的滚动条，面板会固定，没法吸附在输入框周围

2024-06-17 06:44 UTC, sentsim commented
> 可能我给记混了，在`layer`弹窗里自带滚动条时，`laydate`的`position`不管怎么设置，打开面板后，鼠标滚轮滚动`layer`里的滚动条，面板会固定，没法吸附在输入框周围

额，你不是说的外面的滚动条么

2024-06-17 09:49 UTC, sentsim commented
`position` 选项只是针对页面最外层滚动条的错位规避方案。

对于 layer 内部的滚动条进行鼠标滚轮滑动，除了借助 `scroll` 事件同步坐标，组件内部暂时没有太好的方案处理。建议先在外部绑定 layer content 容器的 `scroll` 事件将下拉框移除来规避错位（如下视频所示）。

https://github.com/layui/layui/assets/3277200/9d275485-29a2-4599-bcfd-39143f9ab74b

2024-06-17 10:33 UTC, sentsim approved these changes

2024-06-17 10:35 UTC, merged

2024-07-25 06:27 UTC, mojunyu commented
` javascript

           table.on('toolbar(dataTableFilter)', function (obj) {
                if (obj.event === 'add') {  // 监听添加操作
                    layer.open({
                        title: '添加',
                        type: 2,
                        shade: 0.2,
                        maxmin: true,
                        shadeClose: true,
                        area: ['50%'],
                        content: '/admin/?ct=webPayPayWay&ac=add',
                        success: function(layero, index, that){
                            layer.iframeAuto(index); // 让 iframe 高度自适应
                            that.offset(); // 重新自适应弹层坐标
                        }
                    });
                }
            });`

当type值是2使用iframe打开的页面，即使在select添加 lay-append-to="body" 也会有问题，也会被遮挡，请问一下是什么原因呢？

2024-07-25 14:06 UTC, Sight-wcg commented
> ` javascript
> 
> ```
>        table.on('toolbar(dataTableFilter)', function (obj) {
>             if (obj.event === 'add') {  // 监听添加操作
>                 layer.open({
>                     title: '添加',
>                     type: 2,
>                     shade: 0.2,
>                     maxmin: true,
>                     shadeClose: true,
>                     area: ['50%'],
>                     content: '/admin/?ct=webPayPayWay&ac=add',
>                     success: function(layero, index, that){
>                         layer.iframeAuto(index); // 让 iframe 高度自适应
>                         that.offset(); // 重新自适应弹层坐标
>                     }
>                 });
>             }
>         });`
> ```
> 
> 当type值是2使用iframe打开的页面，即使在select添加 lay-append-to="body" 也会有问题，也会被遮挡，请问一下是什么原因呢？

这是 iframe 的限制，常规方案无解。有一些 hack 方法，参考 https://gitee.com/sun_zoro/layuiTablePlug/blob/master/download/optimizeSelectOption/optimizeSelectOption.js