feat(layer): 新增 beforeEnd 回调
layui/layui pull request #1968
Opened 2024-06-01 15:19 UTC by Sight-wcg

### 😃 本次 PR 的变化性质

> 请至少勾选一项

- [x] 功能新增
- [ ] 问题修复
- [ ] 功能优化
- [ ] 分支合并
- [ ] 其他改动：请在此处填写

### 🌱 本次 PR 的变化内容

- feat(layer): 新增 beforeEnd 回调

### ✅ 本次 PR 的满足条件

> 请在申请合并之前，将符合条件的每一项进行勾选

- [x] 已提供在线演示地址（如：[codepen](https://codepen.io/), [stackblitz](https://stackblitz.com/)）或无需演示
- [x] 已对每一项的改动均测试通过
- [x] 已提供具体的变化内容说明

2024-06-03 03:03 UTC, sentsim approved these changes

2024-06-03 06:03 UTC, sentsim requested changes
@Sight-wcg  该功能可能导致「在逻辑允许关闭的场景下」弹层难以通过相关接口进行关闭的问题。由于 `layer.open` 和 `beforeEnd` 函数都没有返回当前实例对象，所以只能在 success 回调的第三个参数中获取到当前弹层的实例，再 `delete inst.config.beforeEnd` 后，才能实现关闭。如以下场景：

```js
beforeEnd: function(layero, index) {
  var iframeWindow =  window[layero.find('iframe')[0]['name']];
  var elem = iframeWindow.document.querySelector('#id');
  // 阻止默认关闭的条件
  if (elem.value.trim()) {
    if (confirm('关闭后您填写的内容将不会得到保存，确定关闭吗？')) {
      return layer.close(index); // 无法关闭
    };
    return false;
  }
}
```

2024-06-03 16:04 UTC, Sight-wcg commented
> @Sight-wcg 该功能可能导致「在逻辑允许关闭的场景下」弹层难以通过相关接口进行关闭的问题。由于 `layer.open` 和 `beforeEnd` 函数都没有返回当前实例对象，所以只能在 success 回调的第三个参数中获取到当前弹层的实例，再 `delete inst.config.beforeEnd` 后，才能实现关闭。如以下场景：
> 
> ```js
> beforeEnd: function(layero, index) {
>   var iframeWindow =  window[layero.find('iframe')[0]['name']];
>   var elem = iframeWindow.document.querySelector('#id');
>   // 阻止默认关闭的条件
>   if (elem.value.trim()) {
>     if (confirm('关闭后您填写的内容将不会得到保存，确定关闭吗？')) {
>       return layer.close(index); // 无法关闭
>     }
>     return false;
>   }
> }
> ```

现在 beforeEnd 返回值支持 `JQueryDeferred<boolean> | Promise<boolean>`

https://stackblitz.com/edit/vu45xk-mt4huq?file=index.html

2024-06-05 13:07 UTC, sentsim approved these changes

2024-06-05 13:56 UTC, merged

2024-06-28 06:16 UTC, liangchuying commented
怎么不做一个 下拉菜单？？？

2024-06-28 06:19 UTC, sentsim commented
> 怎么不做一个 下拉菜单？？？layer.Dropdown layer.Tip 影响多个layer 弹窗的close, 也是可以解决但是不是真正的下拉框方便

@liangchuying 
https://layui.dev/docs/2/dropdown/ ???

2024-06-28 09:54 UTC, liangchuying commented
> > 怎么不做一个 下拉菜单？？？layer.Dropdown layer.Tip 影响多个layer 弹窗的close, 也是可以解决但是不是真正的下拉框方便
> 
> @liangchuying https://layui.dev/docs/2/dropdown/ ???

撤回撤回