feat(upload): error回调函数增加返回值参数
layui/layui pull request #1988
Opened 2024-06-06 06:40 UTC by Pencil-hzp

### 😃 本次 PR 的变化性质

> 请至少勾选一项

- [x] 功能新增
- [ ] 问题修复
- [ ] 功能优化
- [ ] 分支合并
- [ ] 其他改动：请在此处填写

### 🌱 本次 PR 的变化内容

- feat(upload): error回调函数增加返回值参数
- close #1925 

### ✅ 本次 PR 的满足条件

> 请在申请合并之前，将符合条件的每一项进行勾选

- [x] 已提供在线演示地址（如：[codepen](https://codepen.io/), [stackblitz](https://stackblitz.com/)）或无需演示
- [x] 已对每一项的改动均测试通过
- [x] 已提供具体的变化内容说明

2024-06-06 15:13 UTC, sentsim approved these changes

2024-06-07 09:28 UTC, Sight-wcg requested changes

2024-06-07 09:28 UTC, Sight-wcg commented on src/modules/upload.js
> +        case "FORMAT_ERROR":
JSON 解析异常时，是否需要继续执行 error 回调？例如
```
  upload.render({
    elem: '#test1',
    url: 'https://httpbin.org/status/500',
    force: 'json',
    error: function(index, upload, res){
      console.log('res',res);
    },
  });
```

2024-06-07 16:09 UTC, sentsim commented on src/modules/upload.js
> +        case "FORMAT_ERROR":
我昨天也在犹豫该问题，但此处 JSON 解析格式不同于一般的网络异常，应该不需要在前端进行额外的业务处理，只需要跟 `done` 一样抛出提示即可。

2024-06-08 03:14 UTC, Sight-wcg approved these changes

2024-06-11 06:02 UTC, merged