fix(table): 修复 table 全选时的一些边缘情况
layui/layui pull request #2119
Opened 2024-07-22 04:32 UTC by Sight-wcg

### 😃 本次 PR 的变化性质

> 请至少勾选一项

- [ ] 功能新增
- [x] 问题修复
- [ ] 功能优化
- [ ] 分支合并
- [ ] 其他改动：请在此处填写

### 🌱 本次 PR 的变化内容

- fix(table): 修复 table 全选时的一些边缘情况 close #2116

### ✅ 本次 PR 的满足条件

> 请在申请合并之前，将符合条件的每一项进行勾选

- [x] 已提供在线演示地址（如：[codepen](https://codepen.io/), [stackblitz](https://stackblitz.com/)）或无需演示
- [x] 已对每一项的改动均测试通过
- [x] 已提供具体的变化内容说明

2024-07-31 13:31 UTC, sentsim approved these changes

2024-08-01 05:00 UTC, sentsim commented
晨星，我重新看了下代码，没有太看懂这句判断的用意 😂：
https://github.com/layui/layui/commit/249d6db78ec94329acdb2666391db21bb4d1a2f5#diff-13952582bff0a1aa2ddde6f94079a336fc5ff89fbb220988854ebf97ca7f6b20R1653-R1654

以及，为什么要将「背景色选中」单独提到外面来重新进行循环标注呢
https://github.com/layui/layui/blob/458350899169e27aa3b36c174131b6ce9d800593/src/modules/table.js#L1797-L1819

2024-08-01 06:57 UTC, Sight-wcg commented
thisData 循环的内部，只更新 radio 和单个 checkbox 的行选中样式。全选和多选按照实际找到的 tr DOM 进行更新，而不是每次循环都从所有 tr 中过滤当前行。
主要是为了减少 JS 执行时间，之前这段代码的时间复杂度是指数阶，修改后是线性阶。

2024-08-04 15:19 UTC, sentsim requested changes
我在 #2146 重新整理了 `table.setRowChecked()` ，优化并适配了该 PR 涉及的若干问题。
晨星可看下哪个更可取。

2024-08-04 15:30 UTC, sentsim commented
我在 #2146 重新整理了 `table.setRowChecked()` ，优化并适配了该 PR 涉及的若干问题。
晨星可看下哪个更可取。

2024-08-05 04:11 UTC, closed without merging