lay-creatable 的基础上增加 lay-auto-creatable，增加在下拉失焦、回车时自动添加选项
layui/layui pull request #2167
Opened 2024-08-14 21:58 UTC by doxgosun

1、lay-creatable 的基础上增加 lay-auto-creatable，增加在下拉失焦、回车时自动添加选项 2、增加了按上下按键选择时显示随之改变的功能

### 😃 本次 PR 的变化性质

> 请至少勾选一项

- [x ] 功能新增
- [ ] 问题修复
- [x] 功能优化
- [ ] 分支合并
- [ ] 其他改动：请在此处填写

### 🌱 本次 PR 的变化内容

- 在此处列出本次 PR 的每一项改动内容

### ✅ 本次 PR 的满足条件

> 请在申请合并之前，将符合条件的每一项进行勾选

- [ ] 已提供在线演示地址（如：[codepen](https://codepen.io/), [stackblitz](https://stackblitz.com/)）或无需演示
- [ ] 已对每一项的改动均测试通过
- [ ] 已提供具体的变化内容说明

2024-08-16 05:39 UTC, Sight-wcg requested changes
select `输入框搜索操作`，`方向键操作` 和 `失去焦点`都附加了有效的选中行为，且点击选中第一个空项时无法取消选中，我认为不太合适。

我大概能猜到你想实现什么效果，要实现这些功能，需要明确区分 option 的 `selected`, `active` , `hover` 状态，select 目前的设计不太好实现，只能放到后续大版本改进。

2024-08-16 11:00 UTC, sentsim requested changes

2024-08-16 11:00 UTC, sentsim commented on src/modules/form.js
> +        var events = function(reElem, titleElem, disabled, isSearch, isCreatable, isAppendTo, isAutoCreatable){
该方法的参数太长了，不利于书写，应改成 `options` 形式。

2024-08-16 18:03 UTC, doxgosun commented on src/modules/form.js
> +                if(isAutoCreatable) initValue = input.val();
感谢回复。
我项目里有个用户的输入框，可以输入任何内容并检索已存在内容，所以直接假定任何内容都是正确的，并增加上下选择已有内容，失焦和回车都假定是用户确定输入的行为。
其实就是把 layui的select当做一下带下拉菜单的text input了，这个需求不是很常见，也可以使用其他方式实现。如果认这个功能有存在的必要，我尽量按layui的标准去实现，如果这个功能认为不必要或后面大版本更新会实现，我暂时使用其他方式去实现。
再次感谢 layui，辛苦了，在vue横行时代的坚持。

2024-08-17 03:32 UTC, Sight-wcg commented on src/modules/form.js
> +                if(isAutoCreatable) initValue = input.val();
@sentsim  cc

2024-08-17 05:02 UTC, doxgosun commented on src/modules/form.js
> +              !isAutoCreatable && input.val('');
目的就是无法取消选中项，select 当 text 使用，加个判断就可以让指定参数的select实现text功能

2024-08-17 06:11 UTC, Sight-wcg commented on src/modules/form.js
> +              !isAutoCreatable && input.val('');
> 目的就是无法取消选中项，select 当 text 使用，加个判断就可以让指定参数的select实现text功能

根据你描述的需求，也许用 [autoComplete 组件](https://ant.design/components/auto-complete-cn) 更合适

推荐 
1. twitter 的 typeahead 组件，简单实用 https://github.com/twitter/typeahead.js 
2. algolia 的 autocomplete 组件，功能强大使用门槛高 https://github.com/algolia/autocomplete

2024-08-17 09:55 UTC, sentsim commented on src/modules/form.js
> +                if(isAutoCreatable) initValue = input.val();
@doxgosun dropdown 组件符合你的需求（尽管它不具备 select 的一些功能）。
select 的设计初衷是提供预设的可选项进行选择，如果能够自由输入值，将违背这一初衷，也不符合原生 select 的限定。

当然，早在 v2.9.7 版本中，晨星为 select 提供了 `lay-creatable` 属性，实际上也可以变向实现你的需求，但它的前提是经过开发者和用户的双向允许，即开发者开启该功能，且用户主动确认（回车或点击）。

2024-08-22 10:04 UTC, closed without merging