feat(table) 数据表格支持分别设置表头和表体样式 #1704
layui/layui pull request #2173
Opened 2024-08-18 03:21 UTC by jichuanan

### 😃 本次 PR 的变化性质

> 请至少勾选一项

- [x] 功能新增
- [ ] 问题修复
- [ ] 功能优化
- [ ] 分支合并
- [ ] 其他改动：请在此处填写

### 🌱 本次 PR 的变化内容

- 在此处列出本次 PR 的每一项改动内容
- 表头属性新增thStyle选项，原style属性修改为只作用域tbody中的单元格，以实现数据表格支持分别设置表头和表体样式。

### ✅ 本次 PR 的满足条件

> 请在申请合并之前，将符合条件的每一项进行勾选

- [x] 已提供在线演示地址（如：[codepen](https://codepen.io/), [stackblitz](https://stackblitz.com/)）或无需演示
- [x] 已对每一项的改动均测试通过
- [x] 已提供具体的变化内容说明

2024-08-18 12:16 UTC, sentsim requested changes
没有添加 `thStyle` 表头选项的必要。直接用 `css` 就可以实现相关需求。

```
// 给当前表格主容器自定义 css 样式
css: [
  '.layui-table-body .layui-table td[data-field="username"]{color: blue;}',
  '.layui-table-header .layui-table th[data-field="sign"]{color: red;}'
].join('')
```

https://stackblitz.com/edit/crafbs?file=index.html

css 选项灵活度很高，但却常常被忽略，要充分利用。

2024-08-19 02:50 UTC, jichuanan commented
看到issue https://github.com/layui/layui/issues/1704 中有回复 “将来的版本会考虑改进”，在gitee中 也看到类似的issue https://gitee.com/layui/layui/issues/I8F79X ,自己在实际使用中遇到了类似的问题，所以就修改了一下。
确实直接用css更灵活，对table的dom结果及css掌握要求要高一些。
后续增加这个选项的必要性的话，请关闭这个PR。

2024-08-22 10:04 UTC, closed without merging

2025-05-03 17:59 UTC, qiKaa commented
> 没有添加 `thStyle` 表头选项的必要。直接用 `css` 就可以实现相关需求。
> 
> ```
> // 给当前表格主容器自定义 css 样式
> css: [
>   '.layui-table-body .layui-table td[data-field="username"]{color: blue;}',
>   '.layui-table-header .layui-table th[data-field="sign"]{color: red;}'
> ].join('')
> ```
> 
> https://stackblitz.com/edit/crafbs?file=index.html
> 
> css 选项灵活度很高，但却常常被忽略，要充分利用。

css对齐方式对表格内容无效，对标题有效。

2025-05-03 18:16 UTC, qiKaa commented
> 没有添加 `thStyle` 表头选项的必要。直接用 `css` 就可以实现相关需求。
> 
> ```
> // 给当前表格主容器自定义 css 样式
> css: [
>   '.layui-table-body .layui-table td[data-field="username"]{color: blue;}',
>   '.layui-table-header .layui-table th[data-field="sign"]{color: red;}'
> ].join('')
> ```
> 
> https://stackblitz.com/edit/crafbs?file=index.html
> 
> css 选项灵活度很高，但却常常被忽略，要充分利用。

老版本这样设置可以生效，现在新版本style的对其方式不对表格内容生效。
{ field: 'YYbmbh', title: '部门编号', width: 140, align: 'center', style: 'text-align:left;cursor:pointer;' },