docs(form-select): 更新文档
layui/layui pull request #2176
Opened 2024-08-19 02:28 UTC by hjingsuper

### 😃 本次 PR 的变化性质

> 请至少勾选一项

- [ ] 功能新增
- [ ] 问题修复
- [ ] 功能优化
- [ ] 分支合并
- [x] 其他改动：更新文档

### 🌱 本次 PR 的变化内容

- 添加lay-search 属性说明
- 添加lay-creatable 属性说明

### ✅ 本次 PR 的满足条件

> 请在申请合并之前，将符合条件的每一项进行勾选

- [ ] 已提供在线演示地址（如：[codepen](https://codepen.io/), [stackblitz](https://stackblitz.com/)）或无需演示
- [ ] 已对每一项的改动均测试通过
- [x] 已提供具体的变化内容说明

2024-08-19 11:19 UTC, sentsim approved these changes

2024-08-19 11:19 UTC, sentsim commented on docs/form/select.md
> +    <select lay-search="{caseSensitive:false,fuzzy:true}">
```suggestion
    <select lay-search="{caseSensitive:true}">
```

2024-08-19 11:34 UTC, sentsim requested changes

2024-08-19 11:34 UTC, sentsim commented on docs/form/select.md
> +- `lay-creatable=""`：创建option选项
```suggestion

在 `<select>` 元素上设置 `lay-creatable=""` 可允许创建新的 option，需开启 `lay-search` 后生效。
```

2024-08-19 11:34 UTC, sentsim commented on docs/form/select.md
> +在 `<select>` 元素上设置 `lay-search` 可开启选择框的搜索功能，`lay-search="{caseSensitive:false, fuzzy: false}"`支持设置「是否大小写敏感」和「模糊搜索」
```suggestion
在 `<select>` 元素上设置 `lay-search` 可开启选择框的搜索功能，如：`lay-search="{caseSensitive:false, fuzzy: false}"`，支持的可选项如下：
```

2024-08-19 11:34 UTC, sentsim commented on docs/form/select.md
> +- `fuzzy:true`：开启模糊搜索
```suggestion
- `caseSensitive`：是否区分大小写，默认值 `false`
- `fuzzy`：是否开启模糊匹配，设置 `true` 开启后将忽略匹配字符出现在字符串中的位置。默认值 `false`
```

2024-08-21 10:17 UTC, Sight-wcg approved these changes

2024-08-25 14:17 UTC, sentsim approved these changes

2024-08-25 14:18 UTC, merged