refactor: 重构 dropdown 打开与关闭逻辑
layui/layui pull request #2349
Opened 2024-11-22 03:14 UTC by sentsim

### 😃 本次 PR 的变化性质

> 请至少勾选一项

- [ ] 功能新增
- [x] 问题修复
- [x] 功能优化
- [ ] 分支合并
- [ ] 其他改动：请在此处填写

### 🌱 本次 PR 的变化内容

- 重构 面板打开与关闭的逻辑
- 调整 `closeOnClick` 选项默认值为 `true`，即点击目标元素时自动切换打开与关闭
- 修复 在元素自定义事件中创建实例并立刻显示的报错问题
  - closes #2347

### ✅ 本次 PR 的满足条件

> 请在申请合并之前，将符合条件的每一项进行勾选

- [x] 已提供在线演示地址（如：[codepen](https://codepen.io/), [stackblitz](https://stackblitz.com/)）或无需演示
- [x] 已对每一项的改动均测试通过
- [x] 已提供具体的变化内容说明

2024-11-22 04:00 UTC, sentsim commented
该 PR 部分改动需要 晨星@Sight-wcg 协助确认。

2024-11-22 08:56 UTC, Sight-wcg commented
> 该 PR 部分改动需要 晨星@Sight-wcg 协助确认。

好的，晚上我看一下

2024-11-23 02:55 UTC, Sight-wcg requested changes

2024-11-23 02:55 UTC, Sight-wcg commented on src/modules/dropdown.js
> +      var mainElem = that.mainElem = mainElemExisted;
```suggestion
      that.mainElem = mainElemExisted;
```

2024-11-23 02:55 UTC, Sight-wcg commented on src/modules/dropdown.js
> +      typeof options.close === 'function' && options.close(options.elem);
以下场景触发 close 事件会有异常

1. 点击 A, A 打开
2. 鼠标悬停 B，A 自动关闭，B 打开
3. 此时 A 关闭调用的是 B 的 close 事件

```html
<button id="demoA">demoA</button>
<button id="demoB">demoB</button>
```
```js
dropdown.render({
    elem: '#demoA'
    ,content: '自定义内容  123 '
    ,trigger: 'click'
    ,close: function(){
      console.log('demoA', this.elem);
    }
});
dropdown.render({
    elem: '#demoB'
    ,content: '自定义内容  123 '
    ,trigger: 'hover'
    ,close: function(){
      console.log('demoB', this.elem);
    }
});

```

2024-11-23 02:55 UTC, Sight-wcg commented on src/modules/dropdown.js
> -  var MOD_INDEX = 'layui_'+ MOD_NAME +'_index'; // 模块索引名
一些第三方扩展可能使用了相关的 jQuery Data 缓存判断打开状态

2024-11-24 09:52 UTC, sentsim commented on src/modules/dropdown.js
> +      typeof options.close === 'function' && options.close(options.elem);
已优化该问题。忘了在 remove 中根据传入的 id 查找实例。

2024-11-25 02:47 UTC, Sight-wcg approved these changes

2024-11-25 03:33 UTC, merged