fix(table): 修复 table 在 IE8 下报错问题
layui/layui pull request #2437
Opened 2024-12-26 05:28 UTC by Sight-wcg

### 😃 本次 PR 的变化性质

> 请至少勾选一项

- [ ] 功能新增
- [x] 问题修复
- [ ] 功能优化
- [ ] 分支合并
- [ ] 其他改动：请在此处填写

### 🌱 本次 PR 的变化内容

- fix(table): 修复 table 在 IE8 下报错问题

### ✅ 本次 PR 的满足条件

> 请在申请合并之前，将符合条件的每一项进行勾选

- [x] 已提供在线演示地址（如：[codepen](https://codepen.io/), [stackblitz](https://stackblitz.com/)）或无需演示
- [x] 已对每一项的改动均测试通过
- [x] 已提供具体的变化内容说明

2024-12-26 11:48 UTC, sentsim requested changes

2024-12-26 11:48 UTC, sentsim commented on src/layui.js
> +    return style.getPropertyValue ? style.getPropertyValue(lay.hyphenate(name)) : style.getAttribute(lay.camelize(name));
1. 建议将这两个方法的实现直接写在 getStyle 方法中，避免当未加载 lay 模块时使用 `layui.getStyle()` 时触发报错。layui.js 通常是顶级依赖，如哦它用到了 lay 的相关接口，后者则要提到顶级。否则，在使用  `layui.getStyle()`  必须要保证加载了 lay 模块。
2. 建议仅针对 IE8 做改动，将影响范围保持在最小化。

2024-12-26 11:56 UTC, sentsim commented on src/layui.js
> +    return style.getPropertyValue ? style.getPropertyValue(lay.hyphenate(name)) : style.getAttribute(lay.camelize(name));
比如在 `layui.link()` 方法中，就用到了 `layui.getStyle()` ：https://github.com/layui/layui/blob/b0b387a0fe5cc74777915f7b1997bbf0dd3e542e/src/layui.js#L297

假设某个项目引入的是 `src/layui.js`，且在业务模块中通过  `layui.link()`  加载外部样式，此时若业务模块未加载 lay，将会报错。

2024-12-26 16:00 UTC, Sight-wcg commented on src/layui.js
> +    return style.getPropertyValue ? style.getPropertyValue(lay.hyphenate(name)) : style.getAttribute(lay.camelize(name));
> 1. 建议将这两个方法的实现直接写在 getStyle 方法中，避免当未加载 lay 模块时使用 `layui.getStyle()` 时触发报错。layui.js 通常是顶级依赖，若它用到了 lay 的相关接口，后者则要提到顶级。否则，在使用  `layui.getStyle()`  必须要保证加载了 lay 模块。
> 2. 建议仅针对 IE8 做改动，将影响范围保持在最小化。

已修改

2024-12-27 02:40 UTC, sentsim approved these changes

2024-12-30 05:50 UTC, merged